export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD';
export const REQUEST_RESULTS_PENDING = 'REQUEST_RESULTS_PENDING';
export const REQUEST_RESULTS_SUCCESS = 'REQUEST_RESULTS_SUCCESS';
export const REQUEST_RESULTS_FAIL = "REQUEST_RESULTS_FAIL";